import { makeStyles } from '@mui/styles'

export const useStylesPC = makeStyles({
  'home-page': {
    width: '100%',
    minHeight: '100%',
    display: 'flex',
    flexDirection: 'column',
    '& .content': {
      height: '100%',
      width: '100%',
      display: 'flex',
      flexDirection: 'flex-start',
      backgroundColor: '#F3F2EF',
      '& .left-section': {
        height: '100vh',
        minWidth: '20rem',
        width: '25%',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        '& .left-bar': {
          border: '2px solid #E4E6E6',
          display: 'flex',
          flexDirection: 'column',
          justifyContent: 'flex-start',
          alignItems: 'center',
          borderRadius: '10px',
          width: '15rem',
          height: '25rem',
          '& .title': {
            width: '100%',
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center',
            fontSize: '0.9rem',
            marginTop: '2rem',
            marginBottom: '1rem',
          },
          '& .space-items': {
            display: 'flex',
            flexDirection: 'column',
            justifyContent: 'space-around',
            alignItems: 'center',
            height: '20rem',
          },
        },
      },
      '& .main': {
        width: '75%',
        height: '100%',
        display: 'flex',
        flexDirection: 'column',
        '& .button-container': {
          width: '100%',
          height: '14%',
          minHeight: '5rem',
          display: 'flex',
          alignItems: 'center',
          '& .offers-button': {
            width: '6rem',
            mindWidth: '6rem',
            textTransform: 'none',
            borderRadius: '3px',
            boxShadow: 'none',
            marginRight: '1rem',
          },
          '& .posts-button': {
            width: '6rem',
            mindWidth: '6rem',
            textTransform: 'none',
            borderRadius: '3px',
            boxShadow: 'none',
          },
          '& .active': {
            backgroundColor: 'white !important',
            color: 'black !important',
          },
        },
        '& .offers': {
          // border: '1px solid red',
          display: 'flex',
          flexWrap: 'wrap',
          justifyContent: 'space-evenly',
          alignItems: 'center',
          maxWidth: '58rem',
          marginBottom: '3rem',
        },
        '& .posts': {
          display: 'flex',
          flexDirection: 'column',
          maxWidth: '58rem',
          marginBottom: '3rem',
          // border: '1px solid grey'
        },
      },
    },
  },
})
